### ISSUE TITLE
Say goodbye?

### ISSUE THREAD

**Issue by qq99** [larose/utt#1]
> Say hello when you arrive in the morning:
> `$ utt hello`

How does it know when you leave at night?

**Comment by 1kastner** [comment]
So how does this behave when I am a night coder? Will it just look at my last activity which I started at 23:59 and believe it was the last entry of the day? That would be a bit problematic for me because I could reach that border. Or is this what "hello" is good for? Is it meant in the way that between an activity and a hello the time is ignored? So I could also use hello during the day instead of breaks in case I want so?

I love this project and thanks for your effort and sharing :+1:
