### ISSUE TITLE
Allow spaces in project names?

### ISSUE THREAD

**Issue by mdickinson** [larose/utt#81]
Thank you for this excellent tool! I have a minor feature request: would it be possible to allow spaces in project names? I make heavy use of the "project: task" syntax, but my projects often naturally have spaces in:

Example:
```
$ utt add "test project: just testing"
$ utt add "galactic domination: buy pencils for death star sketches"
```

This currently works, but `test_project` and `galactic domination` aren't recognised as projects, and in the report I see something like:

```
(0h46)    : -- Current Activity --, galactic domination: buy paper for death star blueprint, test project: just testing
```

If the idea seems reasonable, I'm happy to take some time to try to create a PR.

**Comment by larose** [comment]
Hi @mdickinson, I'm glad that you like utt and thanks for the feature request!

The reason behind why project names can't contain spaces or colons is to unambiguously differentiate the project name from the rest of the entry. Otherwise, how would we know that there is no project in `"this is an entry with a : in the middle"`, but that there is one in `"galactic domination: buy pencils for death star sketches"`?

I'm worried that allowing spaces in project names will introduce a breaking change to many users. Of course, there would be many other ways to parse and store project names in utt, but when I created utt 7 years ago I apparently thought it was a good idea to not allow spaces and colons in project names.

Also, I think you can easily work around this limitation by replacing spaces with `-` or `_` in a project name. Example: `utt add "galactic-domination: buy pencils for death star sketches"`.

Given the reasons mentioned above, I would prefer to keep the current behavior.

**Comment by mdickinson** [comment]
Thanks for the response and explanation! I had a feeling I was overlooking something obvious.
